version: '3' 
services:
  lazerpay_main:
    container_name: lazerpay
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: lazerpay
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - lazerpay_main:/var/lib/postgresql/data
  lazerpay_test:
    container_name: lazerpay_test
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: lazerpay_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - lazerpay_test:/var/lib/postgresql/data
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - rabbitmq_go_net

volumes:
  lazerpay_main:
  lazerpay_test:

networks:
  rabbitmq_go_net:
    driver: bridge